# Generated by Django 2.2.5 on 2019-09-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_course',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
