# Generated by Django 2.2.5 on 2019-09-29 22:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190929_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='content',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
    ]
